### ISSUE TITLE
When Child.guest is set, should Child.guest_of be required?

### ISSUE THREAD

**Issue by jm-welch** [fbcp-awanas/website#1]
It would be required if all guests are guests of existing members. It would not be required if there is the possibility of a guest without a clubber inviting them.

**Comment by jennifero469** [comment]
Only if there is an option to type in a name. Sometimes they are guests of an adult, or they saw Awana advertised on the website or sign.

**Comment by jm-welch** [comment]
Works for me. We'll leave it as it is, and add help text to indicate what
to do if the visitor is a guest of an adult or a walk-in.
